# MySQL-Front 5.0  (Build 1.0)

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;


# Host: 172.16.0.2    Database: mostratec_junior
# ------------------------------------------------------
# Server version 5.1.63

#
# Table structure for table projetos_2017
#

DROP TABLE IF EXISTS `projetos_2017`;
CREATE TABLE `projetos_2017` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `stand` int(11) DEFAULT NULL,
  `aprovado` varchar(6) DEFAULT NULL,
  `titulo` varchar(255) DEFAULT NULL,
  `tema` varchar(255) DEFAULT NULL,
  `categoria` varchar(1) DEFAULT NULL,
  `resumo` text,
  `area` varchar(255) DEFAULT NULL,
  `outra_area` varchar(100) DEFAULT NULL,
  `objetivo` varchar(255) DEFAULT NULL,
  `metodologia` varchar(255) DEFAULT NULL,
  `consideracoes` varchar(255) DEFAULT NULL,
  `nome_escola` varchar(100) DEFAULT NULL,
  `nome_diretor` varchar(100) DEFAULT NULL,
  `endereco_escola` varchar(100) DEFAULT NULL,
  `cidade` varchar(50) DEFAULT NULL,
  `estado` varchar(50) DEFAULT NULL,
  `pais` varchar(50) DEFAULT NULL,
  `fone_escola` varchar(50) DEFAULT NULL,
  `email_escola` varchar(50) DEFAULT NULL,
  `tipo` varchar(50) DEFAULT NULL,
  `opcao_pagamento` varchar(50) DEFAULT NULL,
  `nome_o` varchar(50) DEFAULT NULL,
  `sexo_o` varchar(50) DEFAULT NULL,
  `disciplina_o` varchar(50) DEFAULT NULL,
  `outra_funcao_o` varchar(50) DEFAULT NULL,
  `fone_o` varchar(50) DEFAULT NULL,
  `email_o` varchar(50) DEFAULT NULL,
  `nome_coo_1` varchar(50) DEFAULT NULL,
  `sexo_coo_1` varchar(50) DEFAULT NULL,
  `disciplina_coo_1` varchar(50) DEFAULT NULL,
  `outra_funcao_coo_1` varchar(50) DEFAULT NULL,
  `fone_coo_1` varchar(50) DEFAULT NULL,
  `email_coo_1` varchar(50) DEFAULT NULL,
  `nome_coo_2` varchar(50) DEFAULT NULL,
  `sexo_coo_2` varchar(50) DEFAULT NULL,
  `disciplina_coo_2` varchar(50) DEFAULT NULL,
  `outra_funcao_coo_2` varchar(50) DEFAULT NULL,
  `fone_coo_2` varchar(50) DEFAULT NULL,
  `email_coo_2` varchar(50) DEFAULT NULL,
  `nome_aluno_1` varchar(50) DEFAULT NULL,
  `sexo_aluno_1` varchar(50) DEFAULT NULL,
  `data_nasc_1` varchar(50) DEFAULT NULL,
  `turma_1` varchar(50) DEFAULT NULL,
  `email_1` varchar(50) DEFAULT NULL,
  `fone_1` varchar(50) DEFAULT NULL,
  `fluencia_1` varchar(50) DEFAULT NULL,
  `ingles1` varchar(50) DEFAULT NULL,
  `italiano1` varchar(50) DEFAULT NULL,
  `espanhol1` varchar(50) DEFAULT NULL,
  `alemao1` varchar(50) DEFAULT NULL,
  `frances1` varchar(50) DEFAULT NULL,
  `outra1` varchar(50) DEFAULT NULL,
  `outra_qual1` varchar(50) DEFAULT NULL,
  `participou1` varchar(50) DEFAULT NULL,
  `nome_aluno_2` varchar(50) DEFAULT NULL,
  `sexo_aluno_2` varchar(50) DEFAULT NULL,
  `data_nasc_2` varchar(50) DEFAULT NULL,
  `turma_2` varchar(50) DEFAULT NULL,
  `email_2` varchar(50) DEFAULT NULL,
  `fone_2` varchar(50) DEFAULT NULL,
  `fluencia_2` varchar(50) DEFAULT NULL,
  `ingles2` varchar(50) DEFAULT NULL,
  `italiano2` varchar(50) DEFAULT NULL,
  `espanhol2` varchar(50) DEFAULT NULL,
  `alemao2` varchar(50) DEFAULT NULL,
  `frances2` varchar(50) DEFAULT NULL,
  `outra2` varchar(50) DEFAULT NULL,
  `outra_qual2` varchar(50) DEFAULT NULL,
  `participou2` varchar(50) DEFAULT NULL,
  `nome_aluno_3` varchar(50) DEFAULT NULL,
  `sexo_aluno_3` varchar(50) DEFAULT NULL,
  `data_nasc_3` varchar(50) DEFAULT NULL,
  `turma_3` varchar(50) DEFAULT NULL,
  `email_3` varchar(50) DEFAULT NULL,
  `fone_3` varchar(50) DEFAULT NULL,
  `fluencia_3` varchar(50) DEFAULT NULL,
  `ingles3` varchar(50) DEFAULT NULL,
  `italiano3` varchar(50) DEFAULT NULL,
  `espanhol3` varchar(50) DEFAULT NULL,
  `alemao3` varchar(50) DEFAULT NULL,
  `frances3` varchar(50) DEFAULT NULL,
  `outra3` varchar(50) DEFAULT NULL,
  `outra_qual3` varchar(50) DEFAULT NULL,
  `participou3` varchar(50) DEFAULT NULL,
  `nome_aluno_4` varchar(50) DEFAULT NULL,
  `sexo_aluno_4` varchar(50) DEFAULT NULL,
  `data_nasc_4` varchar(50) DEFAULT NULL,
  `turma_4` varchar(50) DEFAULT NULL,
  `email_4` varchar(50) DEFAULT NULL,
  `fone_4` varchar(50) DEFAULT NULL,
  `fluencia_4` varchar(50) DEFAULT NULL,
  `ingles4` varchar(50) DEFAULT NULL,
  `italiano4` varchar(50) DEFAULT NULL,
  `espanhol4` varchar(50) DEFAULT NULL,
  `alemao4` varchar(50) DEFAULT NULL,
  `frances4` varchar(50) DEFAULT NULL,
  `outra4` varchar(50) DEFAULT NULL,
  `outra_qual4` varchar(50) DEFAULT NULL,
  `participou4` varchar(50) DEFAULT NULL,
  `nome_aluno_5` varchar(50) DEFAULT NULL,
  `sexo_aluno_5` varchar(50) DEFAULT NULL,
  `data_nasc_5` varchar(50) DEFAULT NULL,
  `turma_5` varchar(50) DEFAULT NULL,
  `email_5` varchar(50) DEFAULT NULL,
  `fone_5` varchar(50) DEFAULT NULL,
  `fluencia_5` varchar(50) DEFAULT NULL,
  `ingles5` varchar(50) DEFAULT NULL,
  `italiano5` varchar(50) DEFAULT NULL,
  `espanhol5` varchar(50) DEFAULT NULL,
  `alemao5` varchar(50) DEFAULT NULL,
  `frances5` varchar(50) DEFAULT NULL,
  `outra5` varchar(50) DEFAULT NULL,
  `outra_qual5` varchar(50) DEFAULT NULL,
  `participou5` varchar(50) DEFAULT NULL,
  `feira_conveniada` varchar(50) DEFAULT NULL,
  `qual_feira` varchar(255) DEFAULT NULL,
  `municipio` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=370 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
