CREATE DATABASE MOSTRATEC_JUNIOR;

USE MOSTRATEC_JUNIOR;

CREATE TABLE M_CADASTRO(
	C_ID_CADASTRO INT AUTO_INCREMENT,
    C_TIPO_CADASTRO VARCHAR(15),
    C_NOME_INSTITUICAO VARCHAR(80),
    C_RESPONSAVEL_INSTITUICAO VARCHAR(50),
    C_TELEFONE_RESPONSAVEL_INSTITUICAO VARCHAR(15),
    C_EMAIL_REPOSANSAVEL_INSTITUICAO VARCHAR(50),
    C_NOME_FEIRA_DE_CIENCIAS VARCHAR(50),
    C_RUA_FEIRA_DE_CIENCIAS VARCHAR(50),
    C_NUMERO_FEIRA_DE_CIENCIAS INT,
    C_CEP_FEIRA_DE_CIENCIAS INT,
    C_CIDADE_FEIRA_DE_CIENCIAS VARCHAR(50),
    C_UF_FEIRA_DE_CIENCIAS CHAR(2),
    C_PAIS_FEIRA_DE_CIENCIAS VARCHAR(30),
    C_SITE_FEIRA_DE_CIENCIAS VARCHAR(50),
    C_NOME_CORDENADOR_FEIRA VARCHAR(50),
    C_TELEFONE_CORDENADOR_FEIRA VARCHAR(15),
    C_EMAIL_CORDENADOR_FEIRA VARCHAR(50),
    C_NOME_PESSOA_PRA_CONTATO VARCHAR(50),
    C_TELEFONE_PESSOA_PRA_CONTATO VARCHAR(15),
    C_EMAIL_PESSOA_PRA_CONTATO VARCHAR(50),
    C_PERIDIOCIDADE_DA_FEIRA VARCHAR(50),
    C_DATA_REALIZACAO_FEIRA_RECENTE DATE,
    C_DATA_REALIZACAO_FEIRA_PROXIMA DATE,
    C_DATA_CONFIRMADA_FEIRA ENUM('S', 'N'),
    C_NUMERO_EDICAO_FEIRA INT,
    C_TIPO_DE_FEIRA VARCHAR(50),
    C_DESCRICAO_ABRANGENCIA_FEIRA TEXT,
    C_EXISTE_COMITE_REVISAO_CIENTIFICA ENUM('S', 'N'),
    C_DESCRICAO_PROCESSO_DE_SELECAO TEXT,
    C_NUMERO_PROJETOS_PROXIMA_EDICAO INT,
    C_NUMERO_ESCOLAS_PROXIMA_EDICAO INT,
    C_PARTICIPAM_FEIRA_FAIXA_ETARIA_ENSINO_INFANTIL VARCHAR(50),
    C_PARTICIPAM_FEIRA_FAIXA_ETARIA_ENSINO_FUDAMENTAL VARCHAR(50),
    C_PARTICIPAM_FEIRA_FAIXA_ETARIA_ENSINO_MEDIO VARCHAR(50),
    C_PARTICIPAM_FEIRA_FAIXA_ETARIA_ENSINO_SUPERIOR VARCHAR(50),
    C_DESCRICAO_PROCESSO_AVALIACAO_FEIRA TEXT,
    C_DATA_ULTIMA_FEIRA_REALIZADA DATE,
    C_ULTIMA_FEIRA_NUMERO_PROJETOS_UM_ESTUDANTE INT,
    C_ULTIMA_FEIRA_NUMERO_PROJETOS_DOIS_ESTUDANTES INT,
    C_ULTIMA_FEIRA_NUMERO_PROJETOS_TRES_ESTUDANTES INT,
    C_ULTIMA_FEIRA_NUMERO_PROJETOS_QUATRO_ESTUDANTES INT,
    C_ULTIMA_FEIRA_NUMERO_PROJETOS_CINCO_OU_MAIS_ESTUDANTES INT,
    C_ULTIMA_FEIRA_NUMERO_TOTAL_PROFESSORES INT,
    C_ULTIMA_FEIRA_NUMERO_ESCOLAS_PUBLICAS INT,
    C_ULTIMA_FEIRA_NUMERO_ESCOLAS_PRIVADAS INT,
    C_TODOS_PROJETOS_UM_ESTUDANTE INT,
    C_TODOS_PROJETOS_DOIS_ESTUDANTE INT,
    C_TODOS_PROJETOS_TRES_ESTUDANTE INT,
    C_TODOS_PROJETOS_QUATRO_ESTUDANTE INT,
    C_TODOS_PROJETOS_CINCO_OU_MAIS_ESTUDANTE INT,
	C_TODOS_PROJETOS_TOTAL_ESTUDANTES INT,
    C_TODOS_NUMERO_TOTAL_ORIENTADORES INT,
    C_TODOS_NUMERO_ESCOLAS_PUBLICAS INT,
    C_TODOS_NUMERO_ESCOLAS_PRIVADAS INT,
    C_NUMERO_PROJETOS_CREDENCIAMENTO INT,
    C_NUMERO_PROJETOS_DESEJADO_CREDENCIAMENTO INT,
    C_NOME_RESPONSAVEL_PREECHIMENTO_CADASTRO VARCHAR(50),
    C_CARGO_RESPONSAVEL_PREENCHIMENTO_CADASTRO VARCHAR(50),
    C_DATA_CADASTRO DATE,
    CONSTRAINT PK_CADASTRO PRIMARY KEY(C_ID_CADASTRO)
);


CREATE TABLE M_AREAS_DE_PESQUISA(
	A_ID_AREA INT AUTO_INCREMENT,
    A_NOME_AREA VARCHAR(50),
    A_ID_CADASTRO INT,
    CONSTRAINT PK_AREAS_DE_PESQUISA PRIMARY KEY(A_ID_AREA)
);

ALTER TABLE M_AREAS_DE_PESQUISA
ADD CONSTRAINT FK_AREAS_CADASTRO
FOREIGN KEY(A_ID_CADASTRO) REFERENCES M_CADASTRO(C_ID_CADASTRO);

CREATE TABLE M_NIVEL_ENSINO_ESTUDANTES_PROXIMA_EDICAO(
	N_ID_NIVEL INT AUTO_INCREMENT,
    N_TIPO_NIVEL VARCHAR(50),
    N_NUMERO_PROJETOS INT,
    N_NUMERO_ESCOLAS INT,
    N_ID_CADASTRO INT,
    CONSTRAINT PK_NIVEL_ENSINO_ESTUDANTES PRIMARY KEY(N_ID_NIVEL)
);

ALTER TABLE M_NIVEL_ENSINO_ESTUDANTES_PROXIMA_EDICAO
ADD CONSTRAINT FK_NIVEL_CADASTRO
FOREIGN KEY(N_ID_CADASTRO) REFERENCES M_CADASTRO(C_ID_CADASTRO);

SELECT * FROM M_CADASTRO;
SELECT MAX(C_ID_CADASTRO) as '0' FROM M_CADASTRO;
SELECT * FROM M_NIVEL_ENSINO_ESTUDANTES_PROXIMA_EDICAO;